#start service configure
server:
  port: 5678

#wecheat configure
wx:
  app-id: wxf09d0ff55963b2f4
  app-secret: b2d8a1fd9b72c1b60045bc0de14e8b93
  app-get-access-token: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=id&secret=sec
  app-send-msg: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=token

#mysql configure
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/partnerPush?userUnicode=true&characterEncoding=UTF8&useSSL=false